### ISSUE TITLE
Non-root method doesn't work on R

### ISSUE THREAD

**Issue by PreciousWarrior** [itsMoji/Instagram_SSL_Pinning#106]
I cannot install the latest version of the ARM package on Android 11, likely due to an older APK signature scheme. Please update your application. 

`# pm install /path/to/apk.apk`

`Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]`.

Using the GUI I just get an "There was a problem parsing the package" error.

I do not have Instagram already installed, I deleted it.

Here is my device information-:

```
DEVICE
Model: SM-E625F (f62ins)
Manufacturer: samsung
Baseband Version: E625FDDU1AUD1,E625FDDU1AUD1
RIL Version: Samsung RIL v4.0
Build Number: RP1A.200720.012.E625FDDU1AUD1
Build Fingerprint: samsung/f62ins/f62:11/RP1A.200720.012/E625FDDU1AUD1:user/release-keys
Bootloader: E625FDDU1AUD1
Java VM: ART 2.1.0
OS Version: R (11)
SDK: 30

DISPLAY
Resolution: 1080x2400 pixels
Software Density: 420 dpi
Refresh Rate: 60 Hz

PROCESSOR
CPU Architecture: ARMv8-A
Board: exynos9825
Chipset: EXYNOS9825
Cores: 8
Clock Speed: 442 MHz - 2730 MHz
Instruction Sets: arm64-v8a
CPU Features: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm dcpop asimddp
CPU Governor: schedutil
Kernel Version: 4.14.187-21387106-abE625FDDU1AUD1
Kernel Architecture: aarch64
```

**Comment by itsMoji** [comment]
Fixed, Try the latest [ARM](https://github.com/itsMoji/Instagram_SSL_Pinning/tree/master/non-root/arm) version.
