### ISSUE TITLE
Pinning Instagram version SSL v98.0.0.15.119 does not work.

### ISSUE THREAD

**Issue by isK391** [itsMoji/Instagram_SSL_Pinning#11]
I tried it and it doesn't work.

**Comment by isK20** [comment]
Not working Instagram v98.0.0.15.119
![Instagram_v98 0 0 15 119](https://user-images.githubusercontent.com/44727524/60444947-6524ce00-9c48-11e9-8b13-816eefc36cc6.png)

**Comment by GoldenEagle66** [comment]
on 72.0.0.21.98 the same

**Comment by isK391** [comment]
> ngày 72.0.0.21.98 giống nhau

I also your case where both are not working.

**Comment by itsMoji** [comment]
Watch this video https://youtu.be/gmYzlpy2Ii4
