### ISSUE TITLE
Set up proxy on Android

### ISSUE THREAD

**Issue by 89z** [itsMoji/Instagram_SSL_Pinning#111]
In this section [1], it says:

> Run Burp Suite with
> `/<JDK Installation path>/bin/java -jar burpsuite_community.jar` and setting
> up proxy on your Android device.

but it doesnt seem to say how to set up proxy and Android device. Do you have
any instruction?

1. <https://github.com/itsMoji/Instagram_SSL_Pinning#instructions>

**Comment by Nerixyz** [comment]
Might depend on your device and OS but generally you go to your wifi settings and do the advanced settings of an access point. There you'd find a proxy setting.

**Comment by 89z** [comment]
ok but then what? I assume some proxy address would need to be added? I have previously been using HTTP toolkit, and no proxy was required. So any information would be appreciated.

**Comment by Nerixyz** [comment]
You set the hostname and port to the interface and port burp is listening on (and that's not localhost). So if burp is listening on `198.1.2.200:8080` then you set the hostname to `198.1.2.200` and the port to `8080`.

I guess HTTP toolkit installed a VPN that routes requests through the app.

**Comment by 89z** [comment]
How do I know what host and port that Burp is listening on?

**Comment by Nerixyz** [comment]
> How do I know what host and port that Burp is listening on?

`Proxy > Options > Proxy Listeners`. You have to add a listener at the start, that listens on a specific address.

**Comment by 89z** [comment]
OK, how do I "add a listener"?

**Comment by Nerixyz** [comment]
> OK, how do I "add a listener"?

On the right side of the listeners table there is a button with the text `Add`. To add a listener to the list, you have to click the button and navigate through the dialog. 

The address should be accessible from the local network.

**Comment by 89z** [comment]
Looks like an entry is added by default `127.0.0.1:8080` - cant I just leave the default as is and it will work?

**Comment by Nerixyz** [comment]
> cant I just leave the default as is and it will work?

You can leave this entry as is. But this only tells Burp to listen on the loopback address of your machine. However, you want Burp to listen on your local network. For this you have to listen on some other interface (as i described above).

**Comment by 89z** [comment]
> You can leave this entry as is. But this only tells Burp to listen on the loopback address of your machine. However, you want Burp to listen on your local network. For this you have to listen on some other interface (as i described above).

I appreciate all the replies, but I have absolutely no idea what you are talking about. I have been previously using HTTP Toolkit with several APKs no problem. It is only now that I am dealing with this Certificate Pinning bullshit that I am having a problem.

HTTP Tookit doesnt need the user to do any proxy settings, you just start the program, and it monitors the APK traffic.

So if I must enter a "listener", I will try to do it. But what do I enter? I see you have this comment:

> if burp is listening on `198.1.2.200:8080` then you set the hostname to `198.1.2.200` and the port to `8080`.

but you say "IF". I dont know anything about Burp, so I dont know if its even listening, and if it is listening, I dont know what the address is. Thanks again for the comments.

**Comment by Nerixyz** [comment]
> I have been previously using HTTP Toolkit with several APKs no problem.

I don't know HTTP Toolkit. It looks like it does the same as Burp but with less settings and the additional Electron bloat.


> It is only now that I am dealing with this Certificate Pinning bullshit that I am having a problem.

Most apps use certificate pinning. This doesn't have anything to do with the HTTP proxy you use though. I like to use `mitmproxy` for Instagram and it works fine for me. You have to configure every interceptor.

> but you say "IF". I dont know anything about Burp, so I dont know if its even listening, and if it is listening, I dont know what the address is.

To add a new listener, click the `Add` button, select `Specific Address` and the address through which your machine is accessible on your local network. Afterwards you need to install Burp's CA certificate on your phone. There's a guide [here](https://distributedcompute.com/2017/12/12/tech-note-installing-burp-certificate-on-android/). Then you can follow the instructions in the readme.

**Comment by 89z** [comment]
> I don't know HTTP Toolkit. It looks like it does the same as Burp but with less settings and the additional Electron bloat.

I dont care what tool I use, as long as its works. I do not like Electron, but if its the only working option (which is the case for now at least), then I use it.

> Most apps use certificate pinning. This doesn't have anything to do with the HTTP proxy you use though.

I have used several APK with HTTP Toolkit, with no problem. I have used Bandcamp, Google Play, Reddit, SoundCloud, Vimeo, YouTube, and never had to deal with this problem I have with Instagram.

> I like to use `mitmproxy` for Instagram and it works fine for me. You have to configure every interceptor.

If this is better tool, I can try to use it. Do you have link with quickstart or something?

> the address through which your machine is accessible on your local network

I dont know what that is, or how to get it.

**Comment by Nerixyz** [comment]
> If this is better tool, I can try to use it. Do you have link with quickstart or something?

No, not really. It's the same setup as with burp but without a GUI.



> I dont know what that is, or how to get it.

On Windows, you can type `ipconfig` into a console window. Then it says the IPv4 address for your local network. You can select this address in the dropdown in Burp.
