### ISSUE TITLE
Instagram Lite ? 

### ISSUE THREAD

**Issue by SuhatAkbulak** [itsMoji/Instagram_SSL_Pinning#125]
Hello.Do you have pinning for Instagram Lite?

**Comment by x22necek** [comment]
no for now, but I would be glad to see ios version instagram


W dniu niedz., 19.12.2021 o 23:37 Suhat AKBULAK ***@***.***>
napisał(a):

**Comment by elv-py** [comment]
have y

> Hello.Do you have pinning for Instagram Lite?

have you found anything yet, as i also need this

**Comment by GoldLine** [comment]
Instagram Lite is not HTTP Proctocol they have their own Protocol it is hard to unpin also you need to decode packets

**Comment by rwelson** [comment]
SSL Unpin Generic Solution available at www.Unpin.me  for any android app. Instagram, snapchat whatsapp line telegram anything..

**Comment by gaplan** [comment]
Instagram lite using Mqtt protocol @SuhatAkbulak

**Comment by gamerrjoy** [comment]
Hey someone here to help me to unpin instagram ssl
