### ISSUE TITLE
Two libraries needs to be patched in v218.0.0.19.108

### ISSUE THREAD

**Issue by olvinroght** [itsMoji/Instagram_SSL_Pinning#126]
In version v218.0.0.19.108 there's two separate libraries `libliger.so` and `libliger-common.so`, both need to be patched to bypass pinning. 

Here is patched binaries for x86:
[patched_libraries_v218.0.0.19.108.zip](https://github.com/itsMoji/Instagram_SSL_Pinning/files/7901268/patched_libraries_v218.0.0.19.108.zip)

Basically, they splitted one lib, so first patch you should make in `libliger-common.so` and second in `libliger.so`. I am too lazy to make patches for other architectures, sorry :D

**Comment by olvinroght** [comment]
Version v219.0.0.12.117 is the same, it's splitted.

Apk x86 taken from [here](https://apkpure.com/ru/instagram-android/com.instagram.android/variant/219.0.0.12.117-APK), patched and original libs below.
.
[original_libraries_v219.0.0.12.117.zip](https://github.com/itsMoji/Instagram_SSL_Pinning/files/7954009/original_libraries_v219.0.0.12.117.zip)
.
[patched_libraries_v219.0.0.12.117.zip](https://github.com/itsMoji/Instagram_SSL_Pinning/files/7954010/patched_libraries_v219.0.0.12.117.zip)

**Comment by itsMoji** [comment]
Patching only `libliger.so` is enough, why you patch both files?

**Comment by olvinroght** [comment]
No, it's not. If you patch just single file requests don't pass.

**Comment by itsMoji** [comment]
Patching only libliger.so is working fine. Try my version.

**Comment by olvinroght** [comment]
Okay, I looked on your binary. You're using slightly different method and it's working with patching single library. False alarm, sorry.
