### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by leovicio** [itsMoji/Instagram_SSL_Pinning#13]
Even seems like a joke but even following the video still does not work!

I can see the browser history I installed but not the instagram APP

**Comment by Nerixyz** [comment]
It does work. Are you sure you did everything the same?

**Comment by isK391** [comment]
It works very well I am using it.
In here, who is  has the Instagram  views video API, I tried every way I could not catch its hits, and other APIs I caught it. ?

**Comment by Nerixyz** [comment]
@leovicio Make sure you are using Burp >=1.7.36 and Java 11 (JDK >=11.0.3 fixed my issue)
