### ISSUE TITLE
instgram stops directy affter all 

### ISSUE THREAD

**Issue by progl** [itsMoji/Instagram_SSL_Pinning#16]
I tried phone and emulator - proxy is Charles.
Also in Ida tried to fund with no luck< can you explain what to search and why it's crashig(about your's instuction) charles shows facebook and bad req an then it stops and don't launch

**Comment by progl** [comment]
tried third time now instagfram loads - proxy doesnt show text only requests, and in login unknow error

**Comment by Nerixyz** [comment]
Does Charles support TLS 1.3?

**Comment by itsMoji** [comment]
Charles doesn't support TLS 1.3, 
Use Burp Suit with the latest version of Java.

And please watch this video: https://youtu.be/gmYzlpy2Ii4

Regrads
