### ISSUE TITLE
not working ssl unpin

### ISSUE THREAD

**Issue by progl** [itsMoji/Instagram_SSL_Pinning#17]
followed your instruction and sow video - I can do you my own - it doesn't work

installed all aps
open insta it made files
pushed yours lib
opened whithout proxy : 1-1 got error as on video
started burp and installed cert then made wifi to proxy
then startesd app - burp shows cert neogation
done all on linux - what steps to do or its libliger bad?

![image](https://user-images.githubusercontent.com/7974239/61898048-23bed000-af21-11e9-89cb-c6711ea43887.png)

![image](https://user-images.githubusercontent.com/7974239/61897880-bca11b80-af20-11e9-962e-2b7c5d557097.png)

**Comment by progl** [comment]
second run with new lib made too

**Comment by progl** [comment]
can you make new instruction and show site with datetime there?

**Comment by progl** [comment]
mb burp or jdk versions o=play on issue?

**Comment by itsMoji** [comment]
Can you please try with Burp Suit v1.7.36?
You can download it from here: https://portswigger.net/burp/releasesarchive/community
And don't forget to install v1.7.36 certificate on Android.

Regards

**Comment by progl** [comment]
will try a few seconds

**Comment by OzdemirEmrah** [comment]
I have the same problem. I have tried with Burp Suite v1.7.36 it didn't worked.
Android running on virtual device. 
Operating system is Windows.

**Comment by progl** [comment]
installed java se not latest but 11.04 - because burp warning< last version too - but in old works perfect!!!!!
![image](https://user-images.githubusercontent.com/7974239/61904190-faa53c00-af2e-11e9-800c-c89d6fac495b.png)
![image](https://user-images.githubusercontent.com/7974239/61904310-3c35e700-af2f-11e9-8cb3-1c3adf3fd0d8.png)

Can you explain what was patched in smali and ida?
I tried to look several weeks but didn't get a good result! You are genious!
It's very interesting form - not for thanks, I can make regards.

And thank you for your reply!
