### ISSUE TITLE
non rooted apk not working

### ISSUE THREAD

**Issue by bolds07** [itsMoji/Instagram_SSL_Pinning#18]
I download the non rooted versions 

https://github.com/itsMoji/Instagram_SSL_Pinning/tree/master/non-root/arm
https://github.com/itsMoji/Instagram_SSL_Pinning/tree/master/non-root/x86

installed them on my phone and on android studio emulator
config fiddler as mitm exported certificates
config the proxy on devices

after this moment i can see all the traffic going through the devices on fiddler log...

but when i open instagram i get this error

https://ibb.co/vCFV6wV

so i guess you had some errors when compiling this last version

i appreciate any help

**Comment by itsMoji** [comment]
Fiddler doesn't support TLSv1.3,

Please read the requirements and use only Burp suit v1.7.36 with the latest version of Java.

**Comment by bolds07** [comment]
nop...
the error is in the apk you provided, nor burp fiddler or any other proxy will work
the apk itself is unnable to reach internet

even without setting the proxy on android the error appears so the package is probable not even reaching the proxy... if you can you should generate a new one... 

i found another repository with an older version of the apk and worked at first try... but i would like to have a more recent one (even if not the lastest)

**Comment by itsMoji** [comment]
[Watch the tutorial video from 6:18](https://youtu.be/gmYzlpy2Ii4?t=06m18s),

The network error exist in the video too, but after setting the proxy (**only Burp Suit v1.7.36**) it will be gone.

**Comment by bolds07** [comment]
the video you are showing for ROOTED PHONE

i'm using the apk you provided for an UN-ROOTED phone, as it is described at the instructions "more easy"

> Usage
> Download and install patched APK (ARM - x86). (ARM on physical device recommended!)
> 
> Run Burp Suite with /<JDK Installation path>/bin/java -jar burpsuite_community.jar and setting up proxy on your Android device.
> You should install Burp Suite certificate on your Android device
> 
> That's it! Now open the Instagram app on your device and intercept the requests in Burp Suite !

again, the problem is not what i'm doing the problem is at the apk you are putting to download is broken.

i've tryied other repositories about this subject like this  https://github.com/pouyadarabi/Instagram_SSL_Pinning

and it work as a charm just download, trust the cert and spy
but your are the only one with a recent version of instagram, but yours doesn't work

if you could please rebuild the apk with a working version

**Comment by bolds07** [comment]
will you?

**Comment by itsMoji** [comment]
I've tested the patched apk and it's working fine.
If you're using the x86 arch, after setting the proxy the network error message will be gone.

I recommended you to use the ARM version, it's more stable and network error doesn't occur.
