### ISSUE TITLE
Pixel with Android 9 TLSv1.3 problem

### ISSUE THREAD

**Issue by jeudesprits** [itsMoji/Instagram_SSL_Pinning#22]
In Burp:
`the client supported protocol versions [TLSv1.3, (D)TLS--5.26] are not accepted by server preferences [TLS12, TLS11, TLS10, SSL30, SSL20Hello]`

What Im doing wrong?

**Comment by itsMoji** [comment]
Which version of Burp Suite are you using?

**Comment by jeudesprits** [comment]
> Which version of Burp Suite are you using?

java version 12.0.2 
Burp version 2.1.02

Tesedt with Android 9, Android 10, Genymotion Android 7.1 - error. 
But on HTC One with old Android 5 first run I can see request in Burp, second run ... same error.

**Comment by itsMoji** [comment]
Use only Burp Suite v1.7.36 (*.jar version).
You can download it from here: https://portswigger.net/burp/releasesarchive/community

**Comment by jeudesprits** [comment]
> Use only Burp Suite v1.7.36 (*.jar version).
> You can download it from here: https://portswigger.net/burp/releasesarchive/community

Thank you very much. Please continue what you are doing. 

P.S. Facebook use the same lib or another?
