### ISSUE TITLE
Burp Proxy not allowing traffic

### ISSUE THREAD

**Issue by sweetmoniker** [itsMoji/Instagram_SSL_Pinning#25]
Environment:
Windows 10

java version "11.0.4" 2019-07-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.4+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.4+10-LTS, mixed mode)

burpsuite_community_v1.7.36.jar

Genymotion 8.0-API 26

First of all, thanks for what you've done here. I following your tutorial and watched the video. Everything seems like it's going to work, but I cannot log into Instagram. In fact, Burp Proxy isn't allowing any traffic at all. When Burp is running and traffic is redirected through it, I can access http://burp but nothing else. In Burp Suite I can see the requests, but there are no responses. When the proxy is disabled, all internet traffic resolves as expected. I tried mitmproxy to compare, and when enabled it catches chrome browser traffic, but Instagram of course fails. 

I realize this isn't exactly within your purview, but I was wondering if you had any insight as to what I might be doing wrong. Thanks.

**Comment by RMatushkin** [comment]
Did you turn off Proxy Interceptor? It seems like the first request has been caught and the interceptor is waiting for your instructions to forward or cancel.

**Comment by sweetmoniker** [comment]
I did find the "intercept off" button earlier but still had no success. I just tried again and while pages are not resolving in Chrome, I was able to login to Instagram, and everything seems fine in that app. Thanks for mentioning it.

**Comment by itsMoji** [comment]
@RMatushkin Thanks for your help.
