### ISSUE TITLE
x86 not working with Fiddler

### ISSUE THREAD

**Issue by lurumdare** [itsMoji/Instagram_SSL_Pinning#28]
x86 not working with Fiddler

**Comment by lurumdare** [comment]
MEmu 
Xposed 
TrustMeAlready

**Comment by Nerixyz** [comment]
Fiddler does not Support tls 1.3. Use Burp 1 with Java 11+.

**Comment by lurumdare** [comment]
@Nerixyz thanks. I tried it.

**Comment by lurumdare** [comment]
@Nerixyz why need using Java 11+ ?

**Comment by Nerixyz** [comment]
In java 11 tls 1.3 was added

**Comment by lurumdare** [comment]
Okay 
Thanks

All works
