### ISSUE TITLE
Infinity login

### ISSUE THREAD

**Issue by lurumdare** [itsMoji/Instagram_SSL_Pinning#29]
Why?

**Comment by ozican** [comment]
same, is there any solution? I tried all steps several times, even I copied the video.
I tried different JDK versions all > 11
and also I use only bur 1.7.36

**Comment by lurumdare** [comment]
@ozican need disable stepping

**Comment by lurumdare** [comment]
or filter requests

**Comment by ozican** [comment]
I am really really sorry and really thank you for that clue.. Would you show me where is the "disable stepping" or "filter request".

I am sure this will be very useful for all people because I see lots of topics about that.

**Comment by ozican** [comment]
OK I found it, I am sharing an screen now. Thank you very much again! :)

**Comment by lurumdare** [comment]
no problem
