### ISSUE TITLE
How to patch and find signature key

### ISSUE THREAD

**Issue by sorl** [itsMoji/Instagram_SSL_Pinning#34]
It would be super useful if you can share how you patched the .so and how to find the signature key. Thanks!

**Comment by alekstovkach** [comment]
I'd like to know, too.

**Comment by RMatushkin** [comment]
Guys, use Google to find an answer. You should be smart, everything near you, you are able to see that Instagram uses the file libliger.so to prevent MITM.
It wasn't hard to find information about how to patch libliger.so, there's a good article in free space on the Internet. It a little bit old information but it works for me.

**Comment by sorl** [comment]
https://github.com/mgp25/Instagram-API/wiki/Technical-information#extracting-instagrams-signature-key-using-frida (easy)
https://plainsec.org/how-to-bypass-instagram-ssl-pinning-on-android-v78/ (hard)
WorksForMe&trade;
