### ISSUE TITLE
Update ARM

### ISSUE THREAD

**Issue by alekstovkach** [itsMoji/Instagram_SSL_Pinning#36]
Hi. Will there be updates for ARM?

I successfully intercept requests using your any ARM APKs.
On x86 failed after many attempts.

Regards.

**Comment by itsMoji** [comment]
Hi,

Instagram changed something in ARM version so current methods don't work anymore.
I'm working on ARM to disable SSL Pinning but there is no ETA.

For x86, there is one more step comparing to ARM. you should **do a successful network request before setting the burp proxy**. 

Regards.
