### ISSUE TITLE
Burpsuite not support TLS v1.3

### ISSUE THREAD

**Issue by alekstovkach** [itsMoji/Instagram_SSL_Pinning#37]
Hi.

I followed the instructions, but on x86 failed intercept requests. Burpsuite returns an error:
![Screenshot_1](https://user-images.githubusercontent.com/49157883/73472875-d07c7d00-439c-11ea-9365-4a338f1950c1.png)

There is a solution?

Regards.

**Comment by Nerixyz** [comment]
Use Burp 1.7. It's a [known issue](https://support.portswigger.net/customer/portal/questions/17613413-tlsv1-3-not-accepted-by-server-preferences-).

**Comment by alekstovkach** [comment]
> Use Burp 1.7. It's a [known issue](https://support.portswigger.net/customer/portal/questions/17613413-tlsv1-3-not-accepted-by-server-preferences-).

I tried version 1.7., but now the error is returned: no cipher suites in common

![Screenshot_2](https://user-images.githubusercontent.com/49157883/73477297-01f94680-43a5-11ea-9416-35c47fa4b499.png)

**Comment by Nerixyz** [comment]
> 
> 
> > Use Burp 1.7. It's a [known issue](https://support.portswigger.net/customer/portal/questions/17613413-tlsv1-3-not-accepted-by-server-preferences-).
> 
> I tried version 1.7., but now the error is returned: no cipher suites in common
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/49157883/73477297-01f94680-43a5-11ea-9416-35c47fa4b499.png)

Make sure you're running Java 11 or newer (13 or 12 may not work fine).

**Comment by alekstovkach** [comment]
> > > Use Burp 1.7. It's a [known issue](https://support.portswigger.net/customer/portal/questions/17613413-tlsv1-3-not-accepted-by-server-preferences-).
> > 
> > 
> > I tried version 1.7., but now the error is returned: no cipher suites in common
> > ![Screenshot_2](https://user-images.githubusercontent.com/49157883/73477297-01f94680-43a5-11ea-9416-35c47fa4b499.png)
> 
> Make sure you're running Java 11 or newer (13 or 12 may not work fine).

Happened!
Thank you very much!
