### ISSUE TITLE
Can't observe traffic

### ISSUE THREAD

**Issue by uniquefine** [itsMoji/Instagram_SSL_Pinning#39]
Can't observe traffic using the patched app:
- patched app (v126.0.0.25.121) 
- on Ubuntu 19.10 
- with mitmproxy 5.0.1 or Burps suite 2020.2 
- and jdk 11 or 13
- on android studio emulator with Target: google_apis [Google APIs] (API level 25)

If I follow [these steps precisely.](https://github.com/itsMoji/Instagram_SSL_Pinning/blob/master/README.md#usage) I can log in on first start of the app but when I enable the proxy I only get the network error.
Did anyone get this to work recently?

**Comment by itsMoji** [comment]
mimproxy doesn't support tls 1.3
you should only use burpsuite **v1.7.36**
