### ISSUE TITLE
Hi ItsMoji，How can I get Signature Key？

### ISSUE THREAD

**Issue by along923928784** [itsMoji/Instagram_SSL_Pinning#4]
I am not very skilled at IDA. Can you teach me how?

**Comment by itsMoji** [comment]
Hi,
You should extract signature key with Frida, not IDA

**Comment by Amatorios** [comment]
@itsMoji You're able to attach to `com.instagram.android` with Frida and the latest version of Instagram? Mine times out whenever I try to attach to it. Attaching to other processes work, so I assumed there were using some anti-debugging methods. Did you have to do anything special to be able to attach to the process?
