### ISSUE TITLE
It's not work with root and non-root method

### ISSUE THREAD

**Issue by Numenorean** [itsMoji/Instagram_SSL_Pinning#41]
I tried two method, but not once isn't work for me. I got it http://prntscr.com/r6zusd/direct in fiddler

**Comment by Nerixyz** [comment]
> 
> 
> I tried two method, but not once isn't work for me. I got it http://prntscr.com/r6zusd/direct in fiddler

use Burp Version 1

**Comment by Numenorean** [comment]
> > I tried two method, but not once isn't work for me. I got it http://prntscr.com/r6zusd/direct in fiddler
> 
> use Burp Version 1

Now I tried snifing it through burp suite (2020 year version) and I got the same error. I don't see any requests only from Inst

**Comment by Nerixyz** [comment]
Use Burp **VERSION 1**
ONE not TWO, not 2020

**Comment by dsha44** [comment]
I am using burp version 1, still the same error as this guy
