### ISSUE TITLE
Endless login endpoint

### ISSUE THREAD

**Issue by Spixmaster** [itsMoji/Instagram_SSL_Pinning#42]
Hello community,
Basically it works until the point where the https://i.instagram.com/api/v1/accounts/login/ endpoint is called. #29 and #32 have reported the same issue but gave no solution.
I tried it on two of my Linux machines and a Windows PC. I also tried Android 8 and Android 9. The issue remains the same.

I would be very grateful if someone could help me out.

Have a nice day
Matheus

**Comment by cokeless** [comment]
can anyone give a signup endpoint with the respected parameters, thanks.

**Comment by Spixmaster** [comment]
I know what it was for me and for the others that reported this problem. I was used to other proxies like mitmprox, charles, fiddler. I did not know that when interception is on each request needs to be forwarded manually.
So the solution is to turn off intercepting or forwarding the intercepted http requests.
