### ISSUE TITLE
mqtt traffic

### ISSUE THREAD

**Issue by Spixmaster** [itsMoji/Instagram_SSL_Pinning#44]
This repository enables us to intercept the http traffic but what about the mqtt traffic or you know how to do it?

**Comment by itsMoji** [comment]
Sorry I don't know how to capture mqtt traffic

**Comment by IvanMMM** [comment]
I can answer it, if @itsMoji doesn't mind
To capture mqtt(s) traffic, you will need socks proxy, since it's basically tcp connection, not http. Fiddler or Charles can do it, but sure about Burp

**Comment by Spixmaster** [comment]
@IvanMMM I thank you. I did not know where to start but now I know sufficient for a start. Have a nice day.
