### ISSUE TITLE
ARM-Pinning

### ISSUE THREAD

**Issue by Nerixyz** [itsMoji/Instagram_SSL_Pinning#45]
>Instagram changed something in ARM version so current methods don't work anymore.
I'm working on ARM to disable SSL Pinning but there is no ETA.

It would be nice to keep this issue open until ARM is unpinned. In Instagram Threads, the verification happens in `libfizz.so` which is open source: https://github.com/facebookincubator/fizz
It sould be similar to this in the regular app.

**Comment by itsMoji** [comment]
I've patched the latest ARM version and updated the repo.
Thanks for the info.
