### ISSUE TITLE
Phone book

### ISSUE THREAD

**Issue by Mat57** [itsMoji/Instagram_SSL_Pinning#47]
Good afternoon. Help. In the application version 130.0.0.31.121, the contact phone book is not added. Everything works, but the contacts are not loaded. What is the problem?

**Comment by itsMoji** [comment]
Hello,
Please try with the latest ARM version.

**Comment by icelts** [comment]
> Good afternoon. Help. In the application version 130.0.0.31.121, the contact phone book is not added. Everything works, but the contacts are not loaded. What is the problem?

Is it good for your instagram account? I means to avoid your account get ban?
