### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by leovicio** [itsMoji/Instagram_SSL_Pinning#5]
neither one of the options works for me

v72.0.0.21.98 - opens but does not describe requests
v91.0.0.18.118 - after the patched does not open

**Comment by ahvahsky2008** [comment]
same issue

**Comment by gaplan** [comment]
Same

**Comment by itsMoji** [comment]
Hi,
I've added some notes to the Readme file, check it and try the new version.

Regards

**Comment by isK20** [comment]
Same
