### ISSUE TITLE
Add json file with signature data

### ISSUE THREAD

**Issue by 350d** [itsMoji/Instagram_SSL_Pinning#51]
Hello! Can you please add json file to your repo with following info about every app/key you've discovered?
Example for latest version you have here:
```
{
	"vesion_code": "208061744",
	"version": "136.0.0.34.124",
	"signature_key": "46024e8f31e295869a0e861eaed42cb1dd8454b55232d85f6c6764365079374b",
	"signature_key_version": "4",
}
```

**Comment by itsMoji** [comment]
Done with 4ea32bab49b653ef1f74bed590057b5f93401863

Regards
