### ISSUE TITLE
unpack libs.spk

### ISSUE THREAD

**Issue by tsrman** [itsMoji/Instagram_SSL_Pinning#52]
Hi!

Can you explain how i can unpack/pack libs.spk file?
Thanks!

**Comment by bugsel** [comment]
IG remove function getSignatureString?

**Comment by tsrman** [comment]
Yes in 137 version they remove getSignatureString.

**Comment by bugsel** [comment]
no solution found yet?

**Comment by itsMoji** [comment]
Instagram doesn't sign requests in version 137, just SIGNATURE.
Example: 

`signed_body=SIGNATURE.{"phone_id":"51df5a24-e59e-46cd-bc01-fe658aba9f18","_csrftoken":"mPzWvJ399rqCxOY5rn6Bggq7oOcFkf6U","usage":"prefill"}`

**Comment by bugsel** [comment]
@itsMoji but now how to extract out the signature?
