### ISSUE TITLE
can you provide an non root apk for version 100.0.0.17.129

### ISSUE THREAD

**Issue by bolds07** [itsMoji/Instagram_SSL_Pinning#53]
Hello,

Thank you very much for this repository....
I spend a very long time mapping the requests on instagram v100.0.0.17.129

but recently i formated the device i used for making the requests and im not able to find anywhere the instagram 100.0.0.17.129 with ssl pinned.

could you please pin it and upload in this repo?
thanks in advance

**Comment by itsMoji** [comment]
Hello,

x86 or ARM?

**Comment by bolds07** [comment]
x86 please

**Comment by bolds07** [comment]
can you make it?

**Comment by IvanMMM** [comment]
@bolds07, Just check commits history and pick one you need

**Comment by itsMoji** [comment]
Hello,
Sorry for the long wait.
You can download patched Instagram v100.0.0.17.129 x86 (non-root) from [here](https://drive.google.com/open?id=1aWZTpVwHSOpXr8XCgqlUYJ-WV3oKNWCU)

@IvanMMM Thanks for the answer, non-root APK isn't available for version 100.0.0.17.129 in commits history.
