### ISSUE TITLE
Signature of last version of instagram

### ISSUE THREAD

**Issue by ehsansis0** [itsMoji/Instagram_SSL_Pinning#54]
hi my dear
i have a problem with instagram. on my own device instagram version 137.0.0.34.123, when i create account, created account work good without any return challenge or limited. but when i create account with api 136, return challenge and should verify with phone number. i think this problem happened because instagram blocked older api version from last api version. so could you put signature key from 137?
thanks

**Comment by itsMoji** [comment]
Hello,

Check https://github.com/itsMoji/Instagram_SSL_Pinning/issues/52#issuecomment-616125160

Regards

**Comment by icelts** [comment]
> hi my dear
> i have a problem with instagram. on my own device instagram version 137.0.0.34.123, when i create account, created account work good without any return challenge or limited. but when i create account with api 136, return challenge and should verify with phone number. i think this problem happened because instagram blocked older api version from last api version. so could you put signature key from 137?
> thanks

Same to me , I think its not about tha apk vertion.  do you set enc_password work? or just blank it when creat ?
