### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sun/net/ssl/internal/ssl/Provider

### ISSUE THREAD

**Issue by LouenLeoncoeur** [itsMoji/Instagram_SSL_Pinning#56]
Hi, I followed your instructions: downloaded latest version of JDK, burp and tried to run it but got this error:
```java.lang.NoClassDefFoundError: com/sun/net/ssl/internal/ssl/Provider```
I am a newbie in this and have no idea how to figure it out, google didn't help me. Could you please help me somehow?

**Comment by rainb3rry** [comment]
Same error..
