### ISSUE TITLE
challenge_required after account creation

### ISSUE THREAD

**Issue by icelts** [itsMoji/Instagram_SSL_Pinning#57]
I use fresh 4g ip to creat account .And i use v136.0.0.34.124, v133.0.0.32.120, Tested creat by email and phone number.  get this result always. 
{"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/34477325130/xkTp7ER0sZ/", "api_path": "/challenge/34477325130/xkTp7ER0sZ/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}`

I think there must be some mistake i made. Anybody have idear?

**Comment by Nerixyz** [comment]
This isn't related to this repo.

**Comment by icelts** [comment]
> This isn't related to this repo.

Yea, i know. So there is any place i can talk about this?
