### ISSUE TITLE
Instagram Signature Key

### ISSUE THREAD

**Issue by michelmelo** [itsMoji/Instagram_SSL_Pinning#58]
Update to v140.0.0.30.126?

**Comment by icelts** [comment]
Versions greater than 136.0.0.34.124: SIGNATURE
Example: signed_body=SIGNATURE.{"phone_id":"51df5a24-e59e-46cd-bc01-fe658aba9f18","_csrftoken":"mPzWvJ399rqCxOY5rn6Bggq7oOcFkf6U","usage":"prefill"}
