### ISSUE TITLE
patched APK file for 136.0.0.34.124

### ISSUE THREAD

**Issue by samandj15** [itsMoji/Instagram_SSL_Pinning#59]
I can't find patched APK file for V136.0.0.34.124, could you please upload it?
Thanks

**Comment by Nerixyz** [comment]
> I can't find patched APK file for V136.0.0.34.124,

https://github.com/itsMoji/Instagram_SSL_Pinning/tree/0a7aff10eba9c697125070ebfacc50193089f0c4

**Comment by den99552** [comment]
> > I can't find patched APK file for V136.0.0.34.124,
> 
> https://github.com/itsMoji/Instagram_SSL_Pinning/tree/0a7aff10eba9c697125070ebfacc50193089f0c4

how did you do this? how i can see all others versions?

**Comment by Nerixyz** [comment]
> how did you do this?

You can view the commits and then browse the files.
