### ISSUE TITLE
i.instagram.com:443: no cipher suites in common

### ISSUE THREAD

**Issue by 8lbiasian** [itsMoji/Instagram_SSL_Pinning#6]
Hello, 

I follow the steps and still its not working for some reason. 

```
1559437722818 | Proxy | [21]  The client failed to negotiate an SSL connection to i.instagram.com:443: no cipher suites in common
-- | -- | --
```
does this error mean that the patched didn't apply?

this is the command used for 
```
C:\Program Files\Genymobile\Genymotion\tools
λ adb push libliger.so /data/data/com.instagram.android/lib-zstd/libliger.so
libliger.so: 1 file pushed. 80.2 MB/s (5466212 bytes in 0.065s)
```

**Comment by itsMoji** [comment]
Hi,
You're using and older version of Java, the Java version most be >= 11.0.3.
to see what version you've installed, type `java -version` on terminal.

Regards.

**Comment by AndreyBrigunet** [comment]
Hello,
I receive this after relaunching applications
I use the non-root version

`Proxy | [21]  The client failed to negotiate an SSL connection to i.instagram.com:443: no cipher suites in common`

what can be the problem and how do I solve it?

**Comment by Nerixyz** [comment]
> I use the non-root version

What's your Java and Burp version?

**Comment by AndreyBrigunet** [comment]
Burp Suite v1.7.36

![image](https://user-images.githubusercontent.com/7118837/81721103-05ae6600-9488-11ea-8ec4-040653d56c3f.png)

when I first launch the application works
after I close and reopen it after a while it doesn't work anymore

**Comment by Nerixyz** [comment]
You have to use java 11 or newer.

**Comment by AndreyBrigunet** [comment]
with java 11 same problem,
I install the application and it works to see the traffic after I close the application and start it again it doesn't work anymore to see the traffic
