### ISSUE TITLE
Burp Suite 2020.4

### ISSUE THREAD

**Issue by ElectroMyStyle** [itsMoji/Instagram_SSL_Pinning#61]
I tried for a long time to use Burp Suite new version 2020.4 (crack) and I managed to get traffic. You just need to use OpenJDK 12.0.2 and choose only TLS 1.3 and SSLv3 in the settings, the other TLS 1.2, 1.1, etc. settings need to be disabled. Perhaps it will help you or someone else. This will most likely work on other versions of 2++ as well. Good luck!

**Comment by Spixmaster** [comment]
Thanks for the advice.

**Comment by balook** [comment]
im using 2.1.7 and only tls1.2 and sslv3 was there but tls v1.3 was not there

**Comment by XZVB12** [comment]
> im using 2.1.7 and only tls1.2 and sslv3 was there but tls v1.3 was not there
What version of java are you using? most likely you are using a keygen and therefore should use java 8, in which tls 1.3 does not work.

**Comment by Nerixyz** [comment]
> 
> 
> im using 2.1.7 and only tls1.2 and sslv3 was there but tls v1.3 was not there

In 2020.4, Tls 1.3 was officially added.

**Comment by GamiDPC** [comment]
> I tried for a long time to use Burp Suite new version 2020.4 (crack) and I managed to get traffic. You just need to use OpenJDK 12.0.2 and choose only TLS 1.3 and SSLv3 in the settings, the other TLS 1.2, 1.1, etc. settings need to be disabled. Perhaps it will help you or someone else. This will most likely work on other versions of 2++ as well. Good luck!

You can show a screenshot of the settings where I can’t find what to put

**Comment by ElectroMyStyle** [comment]
> > I tried for a long time to use Burp Suite new version 2020.4 (crack) and I managed to get traffic. You just need to use OpenJDK 12.0.2 and choose only TLS 1.3 and SSLv3 in the settings, the other TLS 1.2, 1.1, etc. settings need to be disabled. Perhaps it will help you or someone else. This will most likely work on other versions of 2++ as well. Good luck!
> 
> You can show a screenshot of the settings where I can’t find what to put

Yeah, see settings below. v136 and v140 work fine on Burp Suite 20202.4 with OpenJDK 12.0.2

![BurpSuiteSettings](https://user-images.githubusercontent.com/5159210/81745707-f215f600-94ad-11ea-9fad-54e8a7db4d96.PNG)

**Comment by itsMoji** [comment]
And also you can use Charles for the **ARM version**

**Comment by worakls90** [comment]
Latest working config - 

jdk-14.0.2
burpsuite_pro_v2020.7
apk version  - 151.0.0.23.120

**Comment by rainb3rry** [comment]
Worked on

jdk v15
burp suite v2020.8.1
apk - 165.1.0.29.119
