### ISSUE TITLE
Key v140.0.0.30.126

### ISSUE THREAD

**Issue by tflop** [itsMoji/Instagram_SSL_Pinning#62]
What is the key for version 140.0.0.30.126?

**Comment by Nerixyz** [comment]
There's no signature in this version. It's just `SIGNATURE.{json...}`

**Comment by 350d** [comment]
Is this a typo from Instagram developers or what? Looks like an error on their side, right?

**Comment by aporat** [comment]
I'm also wondering if that's a bug on Instagram side or they decide to remove the signature process.

FYI - I noticed those signatures have not been really made any difference in the past year or so. any signature would pass validation.

**Comment by itsMoji** [comment]
I think it's not a bug and they decided to remove the signature process.
