### ISSUE TITLE
im not getting any gud result with it ...if i changed the lib.so with arm my device is aarch64 bit

### ISSUE THREAD

**Issue by balook** [itsMoji/Instagram_SSL_Pinning#64]
im not getting any gud result with it ...if i changed the lib.so with arm my device is aarch64 bit
my devuce poco miui 12 hn port rom .....i did whatu said root and non root but ..not gud result..if i change libliger.so the app is crashing and if i installed from your github apk ...its givning error as unknowns error if i switch on proxy

**Comment by itsMoji** [comment]
try on an armeabi or x86 device
