### ISSUE TITLE
Proxy	[6]  The client failed to negotiate an SSL connection to graph.instagram.com:443: Received fatal alert: bad_certificate

### ISSUE THREAD

**Issue by den99552** [itsMoji/Instagram_SSL_Pinning#66]
1589752574142 | Proxy | [6]  The client failed to negotiate an SSL connection to i.instagram.com:443: Received fatal alert: bad_certificate

i am using Burp Suite v1.7.36 (*.jar version)
and i am trying Root Method
all was ok with 140 version, 141 dont sniff, please check. Especially this file https://github.com/itsMoji/Instagram_SSL_Pinning/tree/master/x86

**Comment by den99552** [comment]
Cert from Burp i install on virtual.

**Comment by den99552** [comment]
jdk-11.0.5 and jdk-11.0.7 i try

**Comment by itsMoji** [comment]
Try the new version
