### ISSUE TITLE
Non-root Apk

### ISSUE THREAD

**Issue by ocracy** [itsMoji/Instagram_SSL_Pinning#67]
Patched apk not working after proxy

Instagram gives error "An Unknown network error has occured
<img width="621" alt="Screen Shot 2020-05-27 at 14 10 58" src="https://user-images.githubusercontent.com/1062938/83012328-eab12980-a023-11ea-8bf2-e84237917bfa.png">
"

**Comment by itsMoji** [comment]
I've test it and it's working fine.
Make sure you have the right [requirements](https://github.com/itsMoji/Instagram_SSL_Pinning#requirements) and follow the [instruction](https://github.com/itsMoji/Instagram_SSL_Pinning#usage) step by step, specially for x86, open the app, wait a few seconds and close it and then set the proxy.

**Comment by Lorymi** [comment]
@ocracy Has this problem been solved for you?
I have the same problem with the latest version!

**Comment by ocracy** [comment]
@Lorymi i solved this problem by doing same things on Windows PC not Macbook

**Comment by gcaraciolo** [comment]
version 155 is ok for non-root but 157 is not working. do you made any changes in the 155 apk uploaded here?
