### ISSUE TITLE
enc_password

### ISSUE THREAD

**Issue by evgenso** [itsMoji/Instagram_SSL_Pinning#68]
Please help...
How calculate enc_password?

**Comment by itsMoji** [comment]
PHP: 
```php
public static function encryptPassword(
        $password,
        $publicKeyId,
        $publicKey)
    {
        $key = openssl_random_pseudo_bytes(32);
        $iv = openssl_random_pseudo_bytes(12);
        $time = time();

        openssl_public_encrypt($key ,$encryptedAesKey, base64_decode($publicKey));
        $encrypted = openssl_encrypt($password, 'aes-256-gcm', $key, OPENSSL_RAW_DATA, $iv, $tag, strval($time));

        $payload = base64_encode("\x01" | pack('n', intval($publicKeyId)) . $iv . pack('s', strlen($encryptedAesKey)) . $encryptedAesKey . $tag . $encrypted);

        return sprintf('#PWD_INSTAGRAM:4:%s:%s', $time, $payload);
    }
```

Check https://github.com/dilame/instagram-private-api/issues/1010

**Comment by evgenso** [comment]
It is not work...
Original enc_password:
#PWD_INSTAGRAM:4:1591018320:AWm8/bL/ELNvFlwsTYMAAX5kWI5BLJGy1uhhMCV73ZzNrLcNNSkVkK17qBnFliClhuYONyUZRERP8I1E7sBrY6NUU8v6F4MmcjrcPilMl2Bh5WaCECgIflz0Rvmz76LVIZy8sexQ3frMRB4ExI2ZnL7fmJCbE2mRgVvBs6+nWF8EHRJd8mF/ZosVvCf+kxWV0Tr4mAUb0RRCXrO6l/aOLsDfekgXISoiLSwTkVGn7VhSrNq0BIBb4mMcIfgS+ABrFLrcRGTDqo1V6w12yebKFtk/uGj6GnXX7ieCoxWhmff4nT2NsgrS1dZ7G5r2KBjEBTb+mykOHh8B3I1beHgbJ0Qop2eQ9X/gUh1gJXaeFqM5LBpILTZJFU7UN/ZwIwryteUXW78MV8OG7Ev5
enc_password by this function:
#PWD_INSTAGRAM:4:1591018320:AWlOybCkXor/n2BA46UAAYYToVwLtgrLMDXHBHblahbIuiGLiVKHEzxMjAJT/tW2+qTAEQYPqnTa2XMUpnSIm72ezEEQU0nyO0dR92LrouM55fIO3lIZikSsE/h4jKt2Z8WrVpX4WYnuUdIlHHTTeef8KpaiNug9xzY64kZbgiDEVqMNu/QguqrookaAAmy2xyry1hSOrOkur8DTQNs548UrTG9uEHdNpiBZ8FL6SgLi5tJhj6nZGEZ6p0P2gcrxm2dyJ+N0OgyG8FSrsAa1QH67Ck5bLo8aRwP/1yGcr9FJlTKz6twS6g3wy8ACfyehYlPnlnvp32tnH4JKQh2XV8sHIXNYSuXaLghCtkdrvjxLWRwpWmGe1m/Um7VGSjkP3JCNI1rXUkTDZn7S

**Comment by Nerixyz** [comment]
@evgenso What's wrong there?

**Comment by Leesoar** [comment]
Hey guys, this is web enc_password api:

`https://leesoar.com/api-v1/ig?pub_key=20ed90203c457a2f9efc20820c2452403bff6424de39ff9cc928a751e07f6915&pub_id=229&pwd=xxx&t=1596703337&secret_key=a9ad0489a73146c68ec514ffce5cbaba`

the secret_key have 200 times.

* "t" is timestamp
* "pwd" is password
* "version" is pub_version, and default is 10
* "action" default is "enc_password"

It returns:
`{
"code": 1,
"message": "ok",
"enc_password": "#PWD_INSTAGRAM_BROWSER:10:1596703337:AQpQAH4W1vHVVa7730diM49fhY5Cn0CsgfGsZ5zA613WkRJDn3ujkqqwEdtnV7BrjgJsW3zinQ1OrSnTdgU2We72gWztHxM7OW2NSfvVR/4AGuCZGbR8mpk30wEzP4Z9tPLfxmr/o3Nmk6v7",
"pub_key": "20ed90203c457a2f9efc20820c2452403bff6424de39ff9cc928a751e07f6915",
"pub_id": "229",
"pwd": "xxx",
"version": 10,
"t": "1596703337"
}`
