### ISSUE TITLE
Instagram SSL Pinning on Android (ARM) Version 95.0.0.21.124 Not Working

### ISSUE THREAD

**Issue by timonty001** [itsMoji/Instagram_SSL_Pinning#7]
No traffic is intercepted in burpsuite . Seems like instagram is simply ignoring proxy settings but few api calls are intercepted after app starts.

https://i.instagram.com/api/v1/instacrash/log/

I am sure setup is working but patch isn't working well.

**Comment by itsMoji** [comment]
Watch this video https://youtu.be/gmYzlpy2Ii4
