### ISSUE TITLE
Login in new version

### ISSUE THREAD

**Issue by CynicallDude** [itsMoji/Instagram_SSL_Pinning#70]
How can i login in new version? Everytime i login with encrypted password, ig says 'There was an error with your request. Please try again.'

**Comment by icelts** [comment]
You solved this problem?

**Comment by mikechamber** [comment]
that's right, you need help? dm me

**Comment by icelts** [comment]
> that's right, you need help?

i got problem with account creation when encrypt the password, Seems is not only password was encrypted ?

**Comment by Mapl92** [comment]
> > that's right, you need help?
> 
> i got problem with account creation when encrypt the password, Seems is not only password was encrypted ?

It requires password, publickeyid, publickey and timestamp

**Comment by chamberrr** [comment]
> > > that's right, you need help?
> > 
> > 
> > i got problem with account creation when encrypt the password, Seems is not only password was encrypted ?
> 
> It requires password, publickeyid, publickey and timestamp

@icelts if you don't know where to get this data, send request to 'https://i.instagram.com/api/v1/qe/sync/', get header ['ig-set-password-encryption-key-id'] (it is publickeyid) and ['ig-set-password-encryption-pub-key'] (it is publickey)

**Comment by icelts** [comment]
> > > > that's right, you need help?
> > > 
> > > 
> > > i got problem with account creation when encrypt the password, Seems is not only password was encrypted ?
> > 
> > 
> > It requires password, publickeyid, publickey and timestamp
> 
> @icelts if you don't know where to get this data, send request to 'https://i.instagram.com/api/v1/qe/sync/', get header ['ig-set-password-encryption-key-id'] (it is publickeyid) and ['ig-set-password-encryption-pub-key'] (it is publickey)

yea, i know. im using vertion 141 and get
```
ig-set-password-encryption-key-id: 99
ig-set-password-encryption-pub-key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6bkJ1RWtSZDhteGxiclU4aXc0MQp4amQyZGVmbFdnS1F3cmpNbjNNVkFoZzVsdXJtQnIzRFNKdmpPUGQ3aHR4VWlneEJtU2JpRysxdngwSkFTVUNrCjVEV3htWSs4ejBmeDBDb2dRR00wbXNBdUxsWEJySGsweVR0YVFLVHpTbDBEQXpBT0x5ZVJxWTluWllCaVNwVWoKc0ZLYmh4c0lpVDlEdktTazJtb0I3YThybDFTcnBOc2NIT0t4TVFndXpIS2hvVmEzbCtWdGFOSWllUy9oMlNDMApDTU1Pc0o5L2xwRHR5S0xERkMwaUZQb1hSb3NxdWErWjhJRE0vekFBcU9YUmQ1R1JSZ2xSZWN2WFByUzM4T200CnNHRENSTzBhYzBiUWRQSm1Eb2tKM2xDWE9sa0tYdFRMRVQyOXlEa1ViR29uZSs3NGw0UVhqVGV3TGFFL05Cd1oKdHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
```
and use https://github.com/itsMoji/Instagram_SSL_Pinning/issues/68#issuecomment-635252368 this php code to encrypt password.  I got this erro:
`{"account_created": false, "errors": {"email": ["This field is required."], "username": ["This field is required."], "device_id": ["This field is required."], "__all__": ["T\u1ea1o m\u1eadt kh\u1ea9u d\u00e0i t\u1ed1i thi\u1ec3u 6 k\u00fd t\u1ef1."]}, "status": "ok", "error_type": "required, required, required, too_short_password"}`

Do you have any idear?

**Comment by Mapl92** [comment]
> > > > > that's right, you need help?
> > > > 
> > > > 
> > > > i got problem with account creation when encrypt the password, Seems is not only password was encrypted ?
> > > 
> > > 
> > > It requires password, publickeyid, publickey and timestamp
> > 
> > 
> > @icelts if you don't know where to get this data, send request to 'https://i.instagram.com/api/v1/qe/sync/', get header ['ig-set-password-encryption-key-id'] (it is publickeyid) and ['ig-set-password-encryption-pub-key'] (it is publickey)
> 
> yea, i know. im using vertion 141 and get
> 
> ```
> ig-set-password-encryption-key-id: 99
> ig-set-password-encryption-pub-key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6bkJ1RWtSZDhteGxiclU4aXc0MQp4amQyZGVmbFdnS1F3cmpNbjNNVkFoZzVsdXJtQnIzRFNKdmpPUGQ3aHR4VWlneEJtU2JpRysxdngwSkFTVUNrCjVEV3htWSs4ejBmeDBDb2dRR00wbXNBdUxsWEJySGsweVR0YVFLVHpTbDBEQXpBT0x5ZVJxWTluWllCaVNwVWoKc0ZLYmh4c0lpVDlEdktTazJtb0I3YThybDFTcnBOc2NIT0t4TVFndXpIS2hvVmEzbCtWdGFOSWllUy9oMlNDMApDTU1Pc0o5L2xwRHR5S0xERkMwaUZQb1hSb3NxdWErWjhJRE0vekFBcU9YUmQ1R1JSZ2xSZWN2WFByUzM4T200CnNHRENSTzBhYzBiUWRQSm1Eb2tKM2xDWE9sa0tYdFRMRVQyOXlEa1ViR29uZSs3NGw0UVhqVGV3TGFFL05Cd1oKdHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
> ```
> 
> and use [#68 (comment)](https://github.com/itsMoji/Instagram_SSL_Pinning/issues/68#issuecomment-635252368) this php code to encrypt password. I got this erro:
> `{"account_created": false, "errors": {"email": ["This field is required."], "username": ["This field is required."], "device_id": ["This field is required."], "__all__": ["T\u1ea1o m\u1eadt kh\u1ea9u d\u00e0i t\u1ed1i thi\u1ec3u 6 k\u00fd t\u1ef1."]}, "status": "ok", "error_type": "required, required, required, too_short_password"}`
> 
> Do you have any idear?

The encrypt function is not the problem. I use the same php code and it works fine for me. The error must be somewhere else

**Comment by chamberrr** [comment]
> > > > > > that's right, you need help?
> > > > > 
> > > > > 
> > > > > i got problem with account creation when encrypt the password, Seems is not only password was encrypted ?
> > > > 
> > > > 
> > > > It requires password, publickeyid, publickey and timestamp
> > > 
> > > 
> > > @icelts if you don't know where to get this data, send request to 'https://i.instagram.com/api/v1/qe/sync/', get header ['ig-set-password-encryption-key-id'] (it is publickeyid) and ['ig-set-password-encryption-pub-key'] (it is publickey)
> > 
> > 
> > yea, i know. im using vertion 141 and get
> > ```
> > ig-set-password-encryption-key-id: 99
> > ig-set-password-encryption-pub-key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6bkJ1RWtSZDhteGxiclU4aXc0MQp4amQyZGVmbFdnS1F3cmpNbjNNVkFoZzVsdXJtQnIzRFNKdmpPUGQ3aHR4VWlneEJtU2JpRysxdngwSkFTVUNrCjVEV3htWSs4ejBmeDBDb2dRR00wbXNBdUxsWEJySGsweVR0YVFLVHpTbDBEQXpBT0x5ZVJxWTluWllCaVNwVWoKc0ZLYmh4c0lpVDlEdktTazJtb0I3YThybDFTcnBOc2NIT0t4TVFndXpIS2hvVmEzbCtWdGFOSWllUy9oMlNDMApDTU1Pc0o5L2xwRHR5S0xERkMwaUZQb1hSb3NxdWErWjhJRE0vekFBcU9YUmQ1R1JSZ2xSZWN2WFByUzM4T200CnNHRENSTzBhYzBiUWRQSm1Eb2tKM2xDWE9sa0tYdFRMRVQyOXlEa1ViR29uZSs3NGw0UVhqVGV3TGFFL05Cd1oKdHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
> > ```
> > 
> > 
> > and use [#68 (comment)](https://github.com/itsMoji/Instagram_SSL_Pinning/issues/68#issuecomment-635252368) this php code to encrypt password. I got this erro:
> > `{"account_created": false, "errors": {"email": ["This field is required."], "username": ["This field is required."], "device_id": ["This field is required."], "__all__": ["T\u1ea1o m\u1eadt kh\u1ea9u d\u00e0i t\u1ed1i thi\u1ec3u 6 k\u00fd t\u1ef1."]}, "status": "ok", "error_type": "required, required, required, too_short_password"}`
> > Do you have any idear?
> 
> The encrypt function is not the problem. I use the same php code and it works fine for me. The error must be somewhere else

agree with that, it seems like you provide not enough data for registration, as i can see it is email, device_id and password is too short

**Comment by icelts** [comment]
> > > > > > that's right, you need help?
> > > > > 
> > > > > 
> > > > > i got problem with account creation when encrypt the password, Seems is not only password was encrypted ?
> > > > 
> > > > 
> > > > It requires password, publickeyid, publickey and timestamp
> > > 
> > > 
> > > @icelts if you don't know where to get this data, send request to 'https://i.instagram.com/api/v1/qe/sync/', get header ['ig-set-password-encryption-key-id'] (it is publickeyid) and ['ig-set-password-encryption-pub-key'] (it is publickey)
> > 
> > 
> > yea, i know. im using vertion 141 and get
> > ```
> > ig-set-password-encryption-key-id: 99
> > ig-set-password-encryption-pub-key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6bkJ1RWtSZDhteGxiclU4aXc0MQp4amQyZGVmbFdnS1F3cmpNbjNNVkFoZzVsdXJtQnIzRFNKdmpPUGQ3aHR4VWlneEJtU2JpRysxdngwSkFTVUNrCjVEV3htWSs4ejBmeDBDb2dRR00wbXNBdUxsWEJySGsweVR0YVFLVHpTbDBEQXpBT0x5ZVJxWTluWllCaVNwVWoKc0ZLYmh4c0lpVDlEdktTazJtb0I3YThybDFTcnBOc2NIT0t4TVFndXpIS2hvVmEzbCtWdGFOSWllUy9oMlNDMApDTU1Pc0o5L2xwRHR5S0xERkMwaUZQb1hSb3NxdWErWjhJRE0vekFBcU9YUmQ1R1JSZ2xSZWN2WFByUzM4T200CnNHRENSTzBhYzBiUWRQSm1Eb2tKM2xDWE9sa0tYdFRMRVQyOXlEa1ViR29uZSs3NGw0UVhqVGV3TGFFL05Cd1oKdHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
> > ```
> > 
> > 
> > and use [#68 (comment)](https://github.com/itsMoji/Instagram_SSL_Pinning/issues/68#issuecomment-635252368) this php code to encrypt password. I got this erro:
> > `{"account_created": false, "errors": {"email": ["This field is required."], "username": ["This field is required."], "device_id": ["This field is required."], "__all__": ["T\u1ea1o m\u1eadt kh\u1ea9u d\u00e0i t\u1ed1i thi\u1ec3u 6 k\u00fd t\u1ef1."]}, "status": "ok", "error_type": "required, required, required, too_short_password"}`
> > Do you have any idear?
> 
> The encrypt function is not the problem. I use the same php code and it works fine for me. The error must be somewhere else

Thanks for your reply. I was  beset with this problem many days cant solve it still. 
this is the data i post to server:
`signed_body=SIGNATURE.%7B%22is_secondary_account_creation%22%3A%22false%22%2C%22jazoest%22%3A%2222612%22%2C%22tos_version%22%3A%22row%22%2C%22suggestedUsername%22%3A%22%22%2C%22allow_contacts_sync%22%3A%22true%22%2C%22sn_result%22%3A%22GOOGLE_PLAY_UNAVAILABLE%3A%2BSERVICE_INVALID%22%2C%22do_not_auto_login_if_credentials_match%22%3A%22true%22%2C%22phone_id%22%3A%22af5d9101%2Da7e9%2D4097%2Dac6d%2D1ebefe66fb0a%22%2C%22enc_password%22%3A%22%23PWD_INSTAGRAM%3A4%3A1591772581%3AAWOauHMMKdl21dGzFKEAAUWc2TQagzdEEy7eHA0nun7CqLBQHMTgENqP%2BPN83NcHus%2FkWDKXh01qjSEFpbSXYjPmHc9jvYGyo5yWo%2FqsU64VFyS2nTQitrTfOwjp4AUvr0sZ2oL2hYLysjAVZ0g0YFhmf6P2XeU69rhfHU1pN0RuWr6fPyW4a2yqiTZLI9Van0qNbuAUE4y8HdRO632RDWpuftdVyLNPl2fl5rMNK0PmszE1Aj4pEAPeZewISb20Nb2kiLIjm%2B%2BYMha%2FMaV138Uo4m7QuNNCzubQMjK0kNhEUDCsgS2PZSaY9TKkvWg%2FvDhDORIx13vygKVVabCjjLd24IEFkx%2BJ8itRSxRwuRFS87Lbs3d1IbZGg0MFffYq%0A%22%2C%22_csrftoken%22%3A%22Ilfqk9KUIaejyi5QRUBQ5T7UZN8LwNON%22%2C%22username%22%3A%22dong120295wbbauter%22%2C%22first_name%22%3A%22dong120295wbbauter%22%2C%22day%22%3A%2222%22%2C%22adid%22%3A%22df6f5abb%2Dbff6%2D45cb%2D9d47%2D4a0fa14f8375%22%2C%22guid%22%3A%222d09900c%2D27f5%2D4c17%2D8553%2De5b5cf6e9e97%22%2C%22year%22%3A%221998%22%2C%22device_id%22%3A%22android%2Dhxl5t2u15wz9ycq9%22%2C%22_uuid%22%3A%222d09900c%2D27f5%2D4c17%2D8553%2De5b5cf6e9e97%22%2C%22email%22%3A%22dong120295wbbauter%40gmail%2Ecom%22%2C%22month%22%3A%227%22%2C%22sn_nonce%22%3A%22ZG9uZzEyMDI5NXdiYmF1dGVyQGdtYWlsLmNvbXwxNTkxNzcyNTgwfGlqbWRtZ3V0ZGNkanh5anJ2ZWJjZGV6eA%3D%3D%22%2C%22force_sign_up_code%22%3A%22%22%2C%22waterfall_id%22%3A%2228d146e8%2D7e0b%2D41e5%2Db175%2Dd940d98de54c%22%2C%22qs_stamp%22%3A%22%22%2C%22one_tap_opt_in%22%3A%22true%22%7D`

And i get the erro return:

`{"account_created": false, "errors": {"email": ["This field is required."], "username": ["This field is required."], "device_id": ["This field is required."], "__all__": ["T\u1ea1o m\u1eadt kh\u1ea9u d\u00e0i t\u1ed1i thi\u1ec3u 6 k\u00fd t\u1ef1."]}, "status": "ok", "error_type": "required, required, required, too_short_password"}`

The encpassword is encrypt by the php code. Im sure to post the data fully

**Comment by icelts** [comment]
> > > > > > > that's right, you need help?
> > > > > > 
> > > > > > 
> > > > > > i got problem with account creation when encrypt the password, Seems is not only password was encrypted ?
> > > > > 
> > > > > 
> > > > > It requires password, publickeyid, publickey and timestamp
> > > > 
> > > > 
> > > > @icelts if you don't know where to get this data, send request to 'https://i.instagram.com/api/v1/qe/sync/', get header ['ig-set-password-encryption-key-id'] (it is publickeyid) and ['ig-set-password-encryption-pub-key'] (it is publickey)
> > > 
> > > 
> > > yea, i know. im using vertion 141 and get
> > > ```
> > > ig-set-password-encryption-key-id: 99
> > > ig-set-password-encryption-pub-key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6bkJ1RWtSZDhteGxiclU4aXc0MQp4amQyZGVmbFdnS1F3cmpNbjNNVkFoZzVsdXJtQnIzRFNKdmpPUGQ3aHR4VWlneEJtU2JpRysxdngwSkFTVUNrCjVEV3htWSs4ejBmeDBDb2dRR00wbXNBdUxsWEJySGsweVR0YVFLVHpTbDBEQXpBT0x5ZVJxWTluWllCaVNwVWoKc0ZLYmh4c0lpVDlEdktTazJtb0I3YThybDFTcnBOc2NIT0t4TVFndXpIS2hvVmEzbCtWdGFOSWllUy9oMlNDMApDTU1Pc0o5L2xwRHR5S0xERkMwaUZQb1hSb3NxdWErWjhJRE0vekFBcU9YUmQ1R1JSZ2xSZWN2WFByUzM4T200CnNHRENSTzBhYzBiUWRQSm1Eb2tKM2xDWE9sa0tYdFRMRVQyOXlEa1ViR29uZSs3NGw0UVhqVGV3TGFFL05Cd1oKdHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
> > > ```
> > > 
> > > 
> > > and use [#68 (comment)](https://github.com/itsMoji/Instagram_SSL_Pinning/issues/68#issuecomment-635252368) this php code to encrypt password. I got this erro:
> > > `{"account_created": false, "errors": {"email": ["This field is required."], "username": ["This field is required."], "device_id": ["This field is required."], "__all__": ["T\u1ea1o m\u1eadt kh\u1ea9u d\u00e0i t\u1ed1i thi\u1ec3u 6 k\u00fd t\u1ef1."]}, "status": "ok", "error_type": "required, required, required, too_short_password"}`
> > > Do you have any idear?
> > 
> > 
> > The encrypt function is not the problem. I use the same php code and it works fine for me. The error must be somewhere else
> 
> agree with that, it seems like you provide not enough data for registration, as i can see it is email, device_id and password is too short

do you use it for account creation?

**Comment by chamberrr** [comment]
can you send me a repo to your code, if you can? i'd like to see it

**Comment by icelts** [comment]
> can you send me a repo to your code, if you can? i'd like to see it

yea, ofc. but my code is chinese base, i think you can read part of it. how can i send you the code? since i dont want publice it

**Comment by chamberrr** [comment]
> > can you send me a repo to your code, if you can? i'd like to see it
> 
> yea, ofc. but my code is chinese base, i think you can read part of it. how can i send you the code? since i dont want publice it

email: leebowski98@gmail.com

**Comment by icelts** [comment]
> leebowski98@gmail.com

done. check your email

**Comment by bezrazli4n0** [comment]
Not working, i have this error message: "Oops, an error occurred."
And this is request body:
<details>
<summary>Request body</summary>
signed_body=SIGNATURE.{"is_secondary_account_creation":"false","jazoest":"22431","tos_version":"row","suggestedUsername":"","allow_contacts_sync":"true","sn_result":"GOOGLE_PLAY_UNAVAILABLE:+SERVICE_INVALID","do_not_auto_login_if_credentials_match":"true","phone_id":"558937dd-8663-458b-9ec2-ba5a9d1c5476","enc_password":"#PWD_INSTAGRAM:4:1592384939:AanTbhfYcwPuRF12y6kAAVgcRUXnwgU4vXY00RLf39fRll1CnHilyo2qIhs2cXGIBp/ZQwd/1JqWeTK+G1uwvzhZzT6VjkTk4wmXPVaFASYm2fqHq9cm34RoGbhR7e6MoIxKg606hIkkp0dbI+0NoEtMqfFZqpWYQI1tl+hRzQ3B32Ec0pm+0sSmugRTMg9pIN9/vjB9t/ZmFUqGw0y3WMg3GaQV7/WJOhV6yXmip3JmUgByXNuL3g5BejMkNLQMUVLq2nVlDTTg2cmI7lRp9F6ZJD36/HTcg4K6a+ttzWMAquoWWRVETi2b1WuVIO/6lOWRZSf9+8eJf3Fs3WGjEdzL8Q5a6vJFBh3ez/FzN3OKFgVBx/DxOhqq0iCJ/wpVeeOlHIPq0hw8fLjSog==","_csrftoken":"ihIjjqrKVYYU8oAxLzHReY8KSqnw2cjT","username":"genry1.porshe9202","first_name":"Genry+Porshe","day":"2","adid":"","guid":"558937dd-8663-458b-9ec2-ba5a9d1c5476","year":"1985","device_id":"android-e59037deaa9f99bc","_uuid":"558937dd-8663-458b-9ec2-ba5a9d1c5476","email":"genry1.porshe9202@yahoo.com","month":"7","sn_nonce":"YWxiZXJ0LmpvcGluQG1haWwucnV8MTU5MjMzOTIwNXwlSoQ747que8OuJarr9w0IhhoRs9DZLW0=","force_sign_up_code":"","waterfall_id":"179847c2-d60d-4cad-bbe1-cae967b8525b","qs_stamp":"","one_tap_opt_in":"true"}
</details>

**Comment by Leesoar** [comment]
Hey guys, this is web enc_password api:

`https://leesoar.com/api-v1/ig?pub_key=20ed90203c457a2f9efc20820c2452403bff6424de39ff9cc928a751e07f6915&pub_id=229&pwd=xxx&t=1596703337&secret_key=a9ad0489a73146c68ec514ffce5cbaba`

the secret_key have 200 times.

* "t" is timestamp
* "pwd" is password
* "version" is pub_version, and default is 10
* "action" default is "enc_password"

It returns:
`{
"code": 1,
"message": "ok",
"enc_password": "#PWD_INSTAGRAM_BROWSER:10:1596703337:AQpQAH4W1vHVVa7730diM49fhY5Cn0CsgfGsZ5zA613WkRJDn3ujkqqwEdtnV7BrjgJsW3zinQ1OrSnTdgU2We72gWztHxM7OW2NSfvVR/4AGuCZGbR8mpk30wEzP4Z9tPLfxmr/o3Nmk6v7",
"pub_key": "20ed90203c457a2f9efc20820c2452403bff6424de39ff9cc928a751e07f6915",
"pub_id": "229",
"pwd": "xxx",
"version": 10,
"t": "1596703337"
}`
