### ISSUE TITLE
signature_key and version_code for 142.0.0.34.110

### ISSUE THREAD

**Issue by marciopronin** [itsMoji/Instagram_SSL_Pinning#72]
Could you give me the signature_key and version_code for 142.0.0.34.110 ?

**Comment by itsMoji** [comment]
Instagram **does not sign requests** in versions newer than 136.0.0.34.124, it's just `SIGNATURE` string.
Example: `signed_body=SIGNATURE.{"phone_id":"51df5a24-e59e-46cd-bc01-fe658aba9f18","_csrftoken":"mPzWvJ399rqCxOY5rn6Bggq7oOcFkf6U","usage":"prefill"}`
