### ISSUE TITLE
Burp failed to negotiate SSL connection

### ISSUE THREAD

**Issue by achmstein** [itsMoji/Instagram_SSL_Pinning#78]
I'm getting The client failed to negotiate an SSL connection to graph.instagram.com:443: Received fatal alert: unknown_ca

I'm sure I installed Burp certificate. 
I'm using Android 8

**Comment by LearnJava** [comment]
> I'm getting The client failed to negotiate an SSL connection to graph.instagram.com:443: Received fatal alert: unknown_ca
> 
> I'm sure I installed Burp certificate.
> I'm using Android 8

Non-root method do not work in my test. Root method working very good with Genymotion but do not work in Android Studio emulator devices.(IMHO . In my tests)
