### ISSUE TITLE
android-x86 VirtualBox

### ISSUE THREAD

**Issue by damianhodgkiss** [itsMoji/Instagram_SSL_Pinning#8]
Does this work with androidx86 on virtualbox? get it all installed fine but "Unable to refresh feed".  Verified the .so is replaced correctly with matching md5sum.  Proxy works to intercept chrome.  Tried both mitmproxy and Burp.  Seems to be a pinning issue still.

**Comment by itsMoji** [comment]
Watch this video https://youtu.be/gmYzlpy2Ii4
