### ISSUE TITLE
IG requests do not show in burp

### ISSUE THREAD

**Issue by senoracid** [itsMoji/Instagram_SSL_Pinning#81]
Hi, thanks for guide, although I must be doing something wrong but cannot figure out. Am following instructions for the unrooted (recommended) steps, but IG seems to bypass the proxy.

Am using genymotion: pixel xl  8.0

Setup BURP run from the java -jar command
setup a proxy and turn it on
setup IP and port in android modify wifi
install the patched arm apk
run it.

IG works fine, but nothing appears in BURP.

Any pointers you might have on what I'm doing wrong gratefully received

cheers

**Comment by denizaydemir** [comment]
Does burp show any other traffic coming from phone? Also did you check the alert section? If you intercepted the traffic correctly, there you can see the problems. Example: 
1601218375277 | Proxy | The client failed to negotiate an SSL connection to accounts.google.com:443: Received fatal alert: certificate_unknown
This means app has an implemented certificate pinning mechanism. 
Even if you disable certificate pinning, there are few other things before you can read the traffic. Burp 1.7.36 should be run by jdk 11. Also your phone needs to be rooted to make the system(phone) trust user created certificates.

**Comment by denizaydemir** [comment]
By the way, how did you manage to use ig with emulator?

**Comment by senoracid** [comment]
Hi, thanks for getting back to me. I think I must have done something wrong along the way. Some traffic was going through BURP as could see browser traffic.

Solved issue in the end by using a facebook account that had the whitehat settings turn on, then used that account to create an IG account which enables MITM to work easily.

Then managed to get another modified .apk from somewhere and it just worked with fiddler off the bat


cheers

**Comment by denizaydemir** [comment]
Wow. I wasn't aware of a whitehat setting. Are there any drawbacks of enabling whitehat setting? Such as limited api access?

**Comment by senoracid** [comment]
Honestly I don't know. I wasn't aware of it either, but read about whilst researching trying to get the MITM to work and seems it has been a thing for a year+. But for monitoring the requests for a logged in account it works perfectly for me.  It isn't good if you need to monitor the login / signup, for that you will still need a patched APK / remove cert pinning, but for account actions is fine.

**Comment by senoracid** [comment]
https://www.facebook.com/whitehat/researcher-settings/

General info:
https://www.zdnet.com/article/facebook-rolls-out-whitehat-settings-to-help-bug-hunters-analyze-traffic-in-its-mobile-apps/
