### ISSUE TITLE
so file still not patched

### ISSUE THREAD

**Issue by aki263** [itsMoji/Instagram_SSL_Pinning#9]
Hi

I followed all the steps as suggest by you, installed fresh copy of genymotion, launched nexus 5x image with android 8. Next I copied the so file in the folder and without even setting up proxy tried to login in Instagram. It immediately shows up network issue. 

**Not able to login after coping so file without proxy**
 
![image](https://user-images.githubusercontent.com/5713674/60019690-1c02d600-96ac-11e9-9c0f-681c05de3ff2.png)

It would be really helpful if you could screen record your pc while cracking so we all can learn.

**Comment by aki263** [comment]
Patched it myself. Closing issue.

**Comment by timonty001** [comment]
can you tell what should be patcched to make it work ?
