### ISSUE TITLE
burp java 15

### ISSUE THREAD

**Issue by bolds07** [itsMoji/Instagram_SSL_Pinning#92]
the version of burp you provide to download doesn't work on java 15

it shows a popup saying "it wasnt fully tested on java 15.0.1" and then closes

is it possible to use the latest version of burp? what version of java must use?

**Comment by Davincible** [comment]
v11

**Comment by enriquejr99** [comment]
Alternatively, you can use the latest [mitmproxy](https://github.com/mitmproxy/mitmproxy). I believe @itsMoji suggests using Burp v1 because when Burp v2 came out it did not support the latest TLS version at the time.
