### ISSUE TITLE
Cannot disable auto updates, which undos the patch

### ISSUE THREAD

**Issue by austinhuang0131** [itsMoji/Instagram_SSL_Pinning#94]
Monitoring requests does work right after install but ceases to work after relaunch. Since the shopping button popped up I assume Instagram auto-updated.

Tried [this video](https://youtu.be/-yOtd22E4wE) for instructions but the Auto Updates settings simply don't show.

Using ARM on Android 9 + mitmproxy. No root.

**Comment by itsMoji** [comment]
Please try with the latest version, I can't reproduce it.

**Comment by austinhuang0131** [comment]
Still can reproduce it but I guess it's not an auto update. However the shopping/reel buttons did pop up so I assume it definitely patched itself.

This only seems to affect `i.instagram.com` and `scontent-****-*.cdninstagram.com` as the requests simply stop going through the proxy (I use [PCAPDroid](https://github.com/emanuele-f/PCAPdroid) to create a VPN interface, which sends to a SOCKS5 server which is my local mitmproxy). However there's no change in User-Agent.

**Comment by Nerixyz** [comment]
> However the shopping/reel buttons did pop up so I assume it definitely patched itself.

This is just an indication for instagram enabling an experiment. It's not "patching" itself. In the future when rooms are enabled, you could for example use this version where the feature isn't yet enabled, as this can be done remotely.

You probably didn't do everything right.

**Comment by austinhuang0131** [comment]
Okay, sorry, it seems like any VPN interface will not cut it and I must configure the proxy in Wi-Fi (Network settings) instead.
