### ISSUE TITLE
177.0.0.30.119 Signature Key

### ISSUE THREAD

**Issue by dgokhan** [itsMoji/Instagram_SSL_Pinning#95]
Hello friends, i found some information in the instagram api, but could not find v177 signature key:/ anyone know?

VersionCode = "276028050",
AppVersion = "Instagram 177.0.0.30.119",
Capabilities = "3brTvx8=",
SignatureKey = "????????????????????",
BloksVersionId = "38e807d1f50024907c1026934e57bf28a7c421e5ffcdc0a7b0aa31dbd44acd74"

**Comment by Nerixyz** [comment]
There's no signature. It's just `SIGNATURE.`
