### ISSUE TITLE
There was an error with your request. Please try again.","status":"fail"

### ISSUE THREAD

**Issue by Luckydel** [itsMoji/Instagram_SSL_Pinning#97]
URL: https://i.instagram.com/api/v1/accounts/create_validated/
Request:
X-IG-App-Locale: Uk-UA
X-IG-Device-Locale: Uk-UA
X-IG-Mapped-Locale: Uk-UA
X-Pigeon-Session-Id: 8010d2c3-1192-454c-b44a-a015f0f152c9
X-Pigeon-Rawclienttime: 1616692529.560
X-IG-Bandwidth-Speed-KBPS: -1.000
X-IG-Bandwidth-TotalBytes-B: 0
X-IG-Bandwidth-TotalTime-MS: 0
App-Startup-Country: UA
X-Bloks-Version-Id: 38e807d1f50024907c1026934e57bf28a7c421e5ffcdc0a7b0aa31dbd44acd74
X-IG-WWW-Claim: 0
X-Bloks-Is-Layout-RTL: false
X-Bloks-Is-Panorama-Enabled: true
X-IG-Device-ID: 714a964d-2435-428a-bc65-6cbfb451c5f5
X-IG-Android-ID: android-4984cce064de6d63
X-IG-Connection-Type: WIFI
X-IG-Capabilities: 3brTvx8=
X-IG-App-ID: 567067343352427
User-Agent: Instagram 177.0.0.30.119 Android (24/7.0; 480dpi; 1080x1776; Sony; F8331; F8331; qcom; Uk-UA; 276028050)
Accept-Language: Uk-UA
X-MID: YFtAbwABAAE35E4_o6kh1IvfTLIK
IG-INTENDED-USER-ID: 0
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept-Encoding: gzip, deflate
Host: b.i.instagram.com
X-FB-HTTP-Engine: Liger
X-FB-Client-IP: True
X-FB-Server-Cluster: True
Connection: close

signed_body=SIGNATURE.{"is_secondary_account_creation":"false","jazoest":"22421","tos_version":"row","suggestedUsername":"","verification_code":"468815","sn_result":"GOOGLE_PLAY_UNVAILABLE:+SERVICE_INVALID","do_not_auto_login_if_credentials_match":"true","phone_id":"9b6b6436-a24d-408d-b8e2-d6a908c7ab33","enc_password":"#PWD_INSTAGRAM:4:1616943163:AQbZI1Qnu+dS5VJx5kYAAW+T7aiw+A2PNFgdCw5GP4eBIGgUoammL18KQMw0jUJ0hon8bnykByFyiVdknfadBCerkTor9owKCnZzYj2/TETViy3m/mavIjdzaGnzVYv8PjCIKgIdNsbqyWw5PTnhSf3Ukqub3VagtyfRUYa34DKQMeeQu9pa94uElTl2Yu8ch/DUlx6SuKpkQCXvQy4pL9Kq+YqCkDIxJAAwHvferGd8KfZhbb4CMvsyxvursavXNNeNa4iBFzPX0dD6kHlHFjopAgj6e3lXUMt42Ioegua2uqQ7xZQJup9yU+fjw562U1/tK0sLbX1SNuNXi2a6zJGZR52TeV1ya9mhrp9AKZLSsulfDsKZFMlg65wZknvVRw7YLgAmXJZKTQ==","phone_number":"+380678176249","_csrftoken":"bdhzBToxIo3Bkq5fF1DcGeKw60AflFja","username":"ti_ffany1155","first_name":"Tiffany","day":"29","adid":",","guid":"714a964d-2435-428a-bc65-6cbfb451c5f5","year":"1997","device_id":"android-4984cce064de6d63","_uuid":"714a964d-2435-428a-bc65-6cbfb451c5f5","month":"5","sn_nonce":"fDE2MTY5NDMxNjN8YmV5Ym14dXN5eWFs","force_sign_up_code":"","waterfall_id":"52a1b0b7-c1ff-4de7-be90-58083613e67d","qs_stamp":"","has_sms_consent":"true","one_tap_opt_in":"true"}

Response:
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
ig-set-password-encryption-key-id: 6
ig-set-password-encryption-pub-key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFrOHkrcm5VT24xNi9kZ21EcS80NQpscmQrVnVCZUkyVHhCdHhNeWRYVnBWZDN5WVVrQ0RDZmxJdEZ2UVJKWnlNRUZwSlQxZTA5eG5sb0VacmMrTnFCClpHdnVFVVRtZXZ0RmxVSkJQRHpJY2JBSG04bDVUdWhuZllPbjhCTWFiTFNoQXlUc2hXNnFzTUY5bmhuRXgzZ1QKOEozTVlhVVRZNGF4alg4VE53djV5cGFMN3NrNDBCWkxUaHZSNkFmTk5DdFh0cW5HYmdoQnAxc0xpKytWV2x1eApaWlhBZjF6dm8zS3JXMHl5bFArdGhuTms5N24zTm9hL24zdlVtVTQzWWZ1eGN3UEVBRml2Ni9ETzZSYlY4bzBuCmFJb2ZJMGZ1TE5oaHY5WFVMT1A0Q0lZbVY1WkpkT0ZyTzZZNGZmS1dLTFlQc1Z4a3VGcE9IR2tFNXQ3SFpPanMKdXdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
Vary: Accept-Language, Cookie
Content-Language: uk
Date: Sun, 28 Mar 2021 15:52:45 GMT
Strict-Transport-Security: max-age=31536000
Cache-Control: private, no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Sat, 01 Jan 2000 00:00:00 GMT
X-Frame-Options: SAMEORIGIN
content-security-policy: report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com https://*.facebook.com https://*.fbsbx.com https://*.giphy.com; font-src data: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://graphql.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com https://*.i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://*.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests
cross-origin-embedder-policy-report-only: require-corp;report-to="coep"
report-to: {"group": "coep", "max_age": 86400, "endpoints": [{"url": "/security/coep_report/"}]},{"group": "coop", "max_age": 86400, "endpoints": [{"url": "/security/coop_report/"}]}
origin-trial: AuqWincgAuXeuu3KypEMnrrFEJHySaesyJS3EaIH40zvafzrU0Irhb7+5QwZpOqMZrPTjgvFl7Z5jJgy1dNAcQMAAAB6eyJvcmlnaW4iOiJodHRwczovL2luc3RhZ3JhbS5jb206NDQzIiwiZmVhdHVyZSI6IkNyb3NzT3JpZ2luT3BlbmVyUG9saWN5UmVwb3J0aW5nIiwiZXhwaXJ5IjoxNjEzNDExNjYyLCJpc1N1YmRvbWFpbiI6dHJ1ZX0=
cross-origin-opener-policy: same-origin-allow-popups;report-to="coop"
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
x-aed: 41
x-ig-set-www-claim: 0
Access-Control-Expose-Headers: X-IG-Set-WWW-Claim
ig-set-authorization: Bearer IGT:2:
ig-set-ig-u-ig-direct-region-hint: 
ig-set-ig-u-shbid: 
ig-set-ig-u-shbts: 
ig-set-ig-u-rur: 
ig-set-ig-u-ds-user-id: 
Set-Cookie: csrftoken=bdhzBLoxIo3Bkq5fF1DcGeKw60AflFja; Domain=.instagram.com; expires=Sun, 27-Mar-2022 15:52:45 GMT; Max-Age=31449600; Path=/; Secure
X-FB-TRIP-ID: 1679558926
X-FB-Client-IP-Forwarded: 188.163.18.77
X-FB-Server-Cluster-Forwarded: iev1c01
Alt-Svc: h3-29=":443"; ma=3600,h3-27=":443"; ma=3600
Connection: close
Content-Length: 85

{"message":"There was an error with your request. Please try again.","status":"fail"}

What could be the problem?

**Comment by AleksandrTan** [comment]
I've received this message before.
Experimenting with generating a parameter "enc_password", now for a request "https://i.instagram.com/api/v1/accounts/login/" I get this message - {'message': 'Sorry, there was a problem with your request.', 'status': 'fail', 'error_type': 'sentry_block'}
There is an opinion that this is an account blocking, but I'm not 100% sure about that.
Does the "enc_password" generation code work for you correctly?
Can your code log in with an existing account?
Perhaps because of this, you cannot register.

**Comment by kingbotss** [comment]
Send requests by http2 version. 
If you send to request API with http1, errors will be shown. 

Try to sending http2 version.

**Comment by AleksandrTan** [comment]
Okay I will try.
Thanks you.

**Comment by progl** [comment]
> Okay I will try.
> Thanks you.

Did you successfully ?
