### ISSUE TITLE
request ssl unpin apk

### ISSUE THREAD

**Issue by bolds07** [itsMoji/Instagram_SSL_Pinning#98]
Hello,

I've following your github since a while ago and would like to request you help me to unpin the ssl certificate for an apk other than instagram

the app is called kwai 
https://play.google.com/store/apps/details?id=com.kwai.video&hl=en&gl=US

For some reason when i download straight from google play the downloaded app doest run in my emulator... it opens and freezes completely the emulator [x86-64] 

I managed to find a  mirror for the apk which runs normally in the emulator
https://www.apkmirror.com/apk/kwai/kwai-short-video-maker-community/kwai-short-video-maker-community-5-2-1-511054-release/kwai-short-video-maker-community-5-2-1-511054-2-android-apk-download/

But still i've the ssl cert pinned so i cant inspect the traffic with burp
I've breaking my head the past few days trying to bypass it without success so i would like to ask help from you in order to do that

I dont know how much different is to do this with this app comparing to instagram but i guess you can find you way out to accomplish.

Would be possible for you to help me out with that?

thanks in advance

**Comment by Nerixyz** [comment]
It seems like they're using okhttp. You can use [`objection`](https://github.com/sensepost/objection/) to disable ssl-pinning.

**Comment by bolds07** [comment]
all android http api is build on top of okhttp, to not use okhttp someone would need to build something on top of the socket...

i tried objection and didnt work... its "hello world" guide is very non straight forward if you have experience with it and is able to generate the altered apk i would be thankful

**Comment by Nerixyz** [comment]
> all android http api is build on top of okhttp, to not use okhttp someone would need to build something on top of the socket...

No. There are other libraries for HTTP even from Google.

> its "hello world" guide is very non straight forward

True.

**How I always did it:**
You install the apk and then open a frida-server on the device. You run objection to connect to the app (include the package name) and then run `android sslpinning disable`. Now while having this runnig, the checks are bypassed.

**Comment by bolds07** [comment]
> **How I always did it:**
> You install the apk and then open a frida-server on the device. You run objection to connect to the app (include the package name) and then run `android sslpinning disable`. Now while having this runnig, the checks are bypassed.

but then i need to run this everytime i want to open the app in the emulator... this is super annoying

i run ubuntu in an emulator plus another one for the android and keeps this configuration just for disabling ssl pinning is super not convenient
